version: '3.9'

services:
  msu-back:
    build: .
    container_name: bad-test
    restart: unless-stopped
    ports:
      - 5555:5555
    networks:
      - localnet 

networks:
  localnet:
    external: true
    name: localnet