version: "3"

dotenv: ['.env']

tasks:
  run:
    cmds:
      - go run cmd/main.go

  swaginit:
    cmds:
      - swag init --outputTypes go,yaml -g cmd/main.go internal/model

    deploy:
    cmds:
      - git stash
      - git pull
      - docker compose -f prod.yaml build
      - docker compose -f prod.yaml down
      - docker compose -f prod.yaml up -d
