basePath: /
definitions:
  model.Response:
    properties:
      message:
        example: response message
        type: string
    type: object
host: bad-test.foradmin.pp.ua
info:
  contact:
    email: raitermark@proton.me
    name: Mark Raiter
  description: This is an API for BAD test.
  title: BAD test API
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - multipart/form-data
      description: Web service that receives a `.txt` file with numbers and returns
        `min`, `max`, `median`, `average`, `max increasing sequential`, `max decreasing
        sequential` and `execution time` of the numbers.
      parameters:
      - description: Please insert your `.txt` file here
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Find values
      tags:
      - Task
swagger: "2.0"
